export const GET_USERS = "GET_USERS"
export const GET_USER_BY_ID = "GET_USER_BY_ID"
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const EDIT_USER = "EDIT_USER"
export const DELETE_USER = "DELETE_USER"
export const GET_USER = "GET_USER"